name: prod deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    container: pandoc/latex

    steps:
      - uses: actions/checkout@v5

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: Build production output
        run: sh ./build.sh

      - name: Push build to production repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.KIMEODML_GITHUB_KEY }}
        with:
          source-directory: "output"
          destination-github-username: kimeodml
          destination-repository-name: be18-fin-SyncLab-CtrlLine-Frontend
          user-email: ${{ secrets.KIMEODML_ACCOUNT_EMAIL }}
          commit-message: "ðŸš€ Production release: ${{ github.sha }}"
          target-branch: main
